### ISSUE TITLE
Check package.json fields 

### ISSUE THREAD

**Issue by inafact** [p-code-magazine/p-code#6]
DRAFT 

https://github.com/p-code-magazine/p-code/blob/develop/package.json

**Comment by inafact** [comment]
細かいですが、パッケージ名

```@p-code-magazine/p-code```

or 

```p-code```

どっちがいいすかね..（ちなみにスコーププレフィクスなしの```p-code```はまだ空いてるのでパブリッシュ出来そう）
もとはプライベートパッケージ用途のオプションだったと思いますが、@スコープ着けてパブリックにするほうが今っぽいっち今っぽい気もするし、みんな各々のp-codeを作ってくれ！というマインドなら最初から```@p-code-magazine/```でも良いような気もしてます。

あと、```keywords``` の内容も募集中です

- その他公開される項目についての[参考](https://docs.npmjs.com/files/package.json)

**Comment by hysysk** [comment]
各々作って欲しいし、ルール的に新しい方に従うのがお行儀もいいかなと思うので`@p-code-magazine/p-code`で行きましょう。
`keywords`は`livecoding`は入れるとして、他に思いつくのは`poetry`, `esolang`, `music`とかかな。
