### ISSUE TITLE
Refactoring & cleanup

### ISSUE THREAD

**Issue by inafact** [p-code-magazine/p-code#8]
- [x] directory structure
- [x] minimalistic core-code & dependencies
- [ ] improve example application

etc

**Comment by inafact** [comment]
基本的にこちらも

https://github.com/p-code-magazine/p-code/blob/develop

で進めてます。
実装でいうと依存を必要最低限にしてTone.jsだけになるといいなと思ったので

https://github.com/p-code-magazine/p-code/blob/develop/lib/index.js#L84

のあたりに内部でループを回せるようなオプションを付け足しました。

Tone.jsのLoopが[AudioContextのタイムスケジュールに則って実行してくれるはずなんですが](https://github.com/Tonejs/Tone.js/wiki/TransportTime)、若干挙動が変わる気がしており検証中です（..もともとp5のループで回すのが無理矢理だったのか？）。

なにか知見、ベストプラクティスなどありましたらよろしくおねがいします @hysysk

**Comment by hysysk** [comment]
ありがとうございます！
元々が無理矢理な実装ですね。理想的には数値とかを読むのに1フレーム消費するのもやめたいので、今の方向で進めてもらって良いと思います。

**Comment by inafact** [comment]
Outdated
